theme: minima
title: Hello World!
author: jhw-student
email: JHW-Student@Example.com
description: > # this means to ignore newlines until "baseurl:"
  Uses RFC 2606 for the example email. This is a test site used to learn more about github and more specifically github pages.
  There is nothing of interest here.

# social links
twitter_username: No Twitter # DO NOT include the @ character, or else the build will fail!
github_username:  jhw-student # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
